/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package patolli.game.views.pantallas;

import java.awt.Color;

/**
 *
 * @author Alec_
 */
public class AboutPane extends javax.swing.JPanel {

    private ReturnNavigationListener<AboutPane> navigationListener;

    /**
     * Creates new form AboutPane
     */
   public AboutPane(ReturnNavigationListener<AboutPane> navigationListener) {
        this.navigationListener = navigationListener;
        initComponents();
    }

    public ReturnNavigationListener<AboutPane> getReturnNavigationListener() {
        return navigationListener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JToggleButton();
        lblTitulo = new javax.swing.JLabel();
        lblIntegrantes = new javax.swing.JLabel();
        lblIDS = new javax.swing.JLabel();
        scrDescripcion = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblIntegrante0 = new javax.swing.JLabel();
        lblIntegrante1 = new javax.swing.JLabel();
        lblIntegrante2 = new javax.swing.JLabel();
        lblIntegrante3 = new javax.swing.JLabel();
        lblIdIntegrante0 = new javax.swing.JLabel();
        lblIdIntegrante1 = new javax.swing.JLabel();
        lblIdIntegrante2 = new javax.swing.JLabel();
        lblIdIntegrante3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 500));

        btnVolver.setText("Menú Principal");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTitulo.setText("Patolli");

        lblIntegrantes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIntegrantes.setText("Nombres");

        lblIDS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIDS.setText("ID");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("El Patolli fue un juego de azar, uno de los más antiguos de toda América y fue jugado \npor prácticamente toda Mesoamérica. \nEste juego gozaba de gran popularidad ya que en él se hacían apuestas desde \npequeñas semillas hasta grandes cosechas.");
        scrDescripcion.setViewportView(jTextArea1);

        lblIntegrante0.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIntegrante0.setText("Santana Celaya Alec Demian");

        lblIntegrante1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIntegrante1.setText("Ricardo Javier Saavedra Negrete");

        lblIntegrante2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIntegrante2.setText("Alexandra Iveth Rodríguez Castellanos");

        lblIntegrante3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIntegrante3.setText("Josue Emmanuel Flores Carballo");

        lblIdIntegrante0.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdIntegrante0.setText("216750");

        lblIdIntegrante1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdIntegrante1.setText("229351");

        lblIdIntegrante2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdIntegrante2.setText("229949");

        lblIdIntegrante3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdIntegrante3.setText("228704");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIntegrantes)
                    .addComponent(lblIntegrante0)
                    .addComponent(lblIntegrante1)
                    .addComponent(lblIntegrante2)
                    .addComponent(lblIntegrante3)
                    .addComponent(btnVolver))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdIntegrante3)
                    .addComponent(lblIdIntegrante2)
                    .addComponent(lblIdIntegrante0)
                    .addComponent(lblIDS)
                    .addComponent(lblIdIntegrante1))
                .addContainerGap(450, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(scrDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntegrantes)
                    .addComponent(lblIDS))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntegrante0)
                    .addComponent(lblIdIntegrante0))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntegrante1)
                    .addComponent(lblIdIntegrante1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntegrante2)
                    .addComponent(lblIdIntegrante2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntegrante3)
                    .addComponent(lblIdIntegrante3))
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
         getReturnNavigationListener().returnFrom(AboutPane.this);
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnVolver;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblIDS;
    private javax.swing.JLabel lblIdIntegrante0;
    private javax.swing.JLabel lblIdIntegrante1;
    private javax.swing.JLabel lblIdIntegrante2;
    private javax.swing.JLabel lblIdIntegrante3;
    private javax.swing.JLabel lblIntegrante0;
    private javax.swing.JLabel lblIntegrante1;
    private javax.swing.JLabel lblIntegrante2;
    private javax.swing.JLabel lblIntegrante3;
    private javax.swing.JLabel lblIntegrantes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane scrDescripcion;
    // End of variables declaration//GEN-END:variables
}
