/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package patolli.game.views.pantallas;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Alec_
 */
public class MasterPane extends javax.swing.JPanel {

    private MenuPane menuPane;

    /**
     * Creates new form MasterPane
     */
    public MasterPane() {
        initComponents();
        setLayout(new BorderLayout());
        presentMenu();
    }

    protected void presentMenu() {
        removeAll();

        if (menuPane == null) {
            menuPane = new MenuPane(new MenuPane.NavigationListener() {
                @Override
                public void presentAboutPane(MenuPane source) {
                    AboutPane aboutPane = new AboutPane((AboutPane source1) -> {
                        presentMenu();
                    });
                    present(aboutPane);
                }

                @Override
                public void presentRulesPane(MenuPane source) {
                    RulesPane rulesPane = new RulesPane((RulesPane source1) -> {
                        presentMenu();
                    });
                    present(rulesPane);
                }
            });
        }

        add(menuPane);
        revalidate();
        repaint();
    }

    protected void present(JPanel panel) {
        removeAll();
        add(panel);
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
